"""Add invoice tables - invoices and invoice_items

Revision ID: 007258c802e7
Revises: 9a85066297e9
Create Date: 2025-11-08 06:24:24.145651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007258c802e7'
down_revision = '9a85066297e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
