"""Add status column to invoices

Revision ID: 6468534d376a
Revises: 9c6b23f3335b
Create Date: 2025-11-06 12:51:07.007083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6468534d376a'
down_revision: Union[str, Sequence[str], None] = '9c6b23f3335b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_column('invoices', 'status')
    # ### end Alembic commands ###
