"""add_currency_and_dates_to_invoices

Revision ID: a602e1e6d3d4
Revises: 6468534d376a
Create Date: 2025-11-06 17:44:15.850019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a602e1e6d3d4'
down_revision: Union[str, Sequence[str], None] = '6468534d376a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_date', sa.Date(), nullable=True))
    op.add_column('invoices', sa.Column('currency_code', sa.String(length=3), nullable=True))
    op.add_column('invoices', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('invoices', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'updated_at')
    op.drop_column('invoices', 'created_at')
    op.drop_column('invoices', 'currency_code')
    op.drop_column('invoices', 'invoice_date')
    # ### end Alembic commands ###
