"""Add invoice and email credential tables

Revision ID: e58ce317a974
Revises: 007258c802e7
Create Date: 2025-11-08 06:43:36.999170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e58ce317a974'
down_revision = '007258c802e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_credentials_user_id', table_name='email_credentials')
    op.drop_table('email_credentials')
    op.drop_index('ix_email_processing_logs_user_id', table_name='email_processing_logs')
    op.drop_table('email_processing_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_processing_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_credential_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_message_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_subject', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_from', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('attachments_found', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attachments_processed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoices_created', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='email_processing_logs_pkey')
    )
    op.create_index('ix_email_processing_logs_user_id', 'email_processing_logs', ['user_id'], unique=False)
    op.create_table('email_credentials',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('oauth_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('oauth_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('imap_server', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('imap_port', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imap_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('imap_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('use_ssl', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('polling_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('polling_interval_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_poll_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_poll_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('folder_to_watch', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mark_as_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='email_credentials_pkey')
    )
    op.create_index('ix_email_credentials_user_id', 'email_credentials', ['user_id'], unique=True)
    # ### end Alembic commands ###
